export const GET_ALL_CANDIDATES = 'GET_ALL_CANDIDATES'

export const UPDATE_CANDIDATE = 'UPDATE_CANDIDATE'

export const CREATE_NEW_CANDIDATE = 'CREATE_NEW_CANDIDATE'

/*** CREATE NEW CALL FOR CANDIDATE ***/
export const CREATE_NEW_CALL = 'CREATE_NEW_CALL'


/*** CREATE NEW APPLICATION FOR CANDIDATE ***/
export const CREATE_APPLICATION_FOR_CANDY = 'CREATE_APPLICATION_FOR_CANDY'