export const GET_ALL_COMPANIES = 'GET_ALL_COMPANIES'

export const UPDATE_COMPANY = 'UPDATE_COMPANY'

export const CREATE_NEW_COMPANY = 'CREATE_NEW_COMPANY'

/*** CREATE NEW CLIENT_CALL FOR COMPANY ***/
export const CREATE_NEW_CALL_FOR_COMPANY = 'CREATE_NEW_CALL_FOR_COMPANY'

/*** CREATE NEW JOB FOR COMPANY ***/
export const CREATE_JOB_FOR_COMPANY = 'CREATE_JOB_FOR_COMPANY'